export const mainKittens = [
	{ src: '/Kittens/Portrait/kitten3.webp', width: 2, height: 2 },
	{ src: '/Kittens/Landscape/kitten2.webp', width: 5, height: 3 },
	{ src: '/Kittens/Landscape/kitten4.webp', width: 5, height: 3 },
	{ src: '/Kittens/Portrait/kitten4.webp', width: 2, height: 2 },
	{ src: '/Kittens/Landscape/kitten7.webp', width: 5, height: 3 },
	{ src: '/Kittens/Portrait/kitten8.webp', width: 2, height: 2 },
	{ src: '/Kittens/Portrait/kitten0.webp', width: 2, height: 2 },
	{ src: '/Kittens/Landscape/kitten8.webp', width: 5, height: 3 },
	{ src: '/Kittens/Portrait/kitten1.webp', width: 2, height: 2 },
	{ src: '/Kittens/Landscape/kitten13.webp', width: 6, height: 3 },
	{ src: '/Kittens/Portrait/kitten2.webp', width: 2, height: 2 },
	{ src: '/Kittens/Landscape/kitten12.webp', width: 5, height: 3 },
	{ src: '/Kittens/Portrait/kitten5.webp', width: 2, height: 2 },
	{ src: '/Kittens/Landscape/kitten14.webp', width: 6, height: 3 },
	{ src: '/Kittens/Portrait/kitten6.webp', width: 2, height: 2 },
	{ src: '/Kittens/Landscape/kitten15.webp', width: 5, height: 3 },
	{ src: '/Kittens/Portrait/kitten7.webp', width: 2, height: 2 },
	{ src: '/Kittens/Portrait/kitten9.webp', width: 2, height: 2 },
	{ src: '/Kittens/Portrait/kitten10.webp', width: 2, height: 2 },
	{ src: '/Kittens/Portrait/kitten11.webp', width: 2, height: 2 },
	{ src: '/Kittens/Portrait/kitten12.webp', width: 2, height: 2 },
	{ src: '/Kittens/Portrait/kitten13.webp', width: 2, height: 2 },
	{ src: '/Kittens/Portrait/kitten14.webp', width: 2, height: 2 },
	{ src: '/Kittens/Portrait/kitten15.webp', width: 2, height: 2 }
];

// export const mainKittens = [
// 	'/Kittens/Landscape/kitten2.webp',
// 	'/Kittens/Landscape/kitten4.webp',
// 	'/Kittens/Landscape/kitten7.webp',
// 	'/Kittens/Landscape/kitten8.webp',
// 	'/Kittens/Landscape/kitten12.webp',
// 	'/Kittens/Landscape/kitten13.webp',
// 	'/Kittens/Landscape/kitten14.webp',
// 	'/Kittens/Landscape/kitten15.webp'
// ];

export const kittensPortrait = [
	'/Kittens/Portrait/kitten0.webp',
	'/Kittens/Portrait/kitten1.webp',
	'/Kittens/Portrait/kitten2.webp',
	'/Kittens/Portrait/kitten3.webp',
	'/Kittens/Portrait/kitten4.webp',
	'/Kittens/Portrait/kitten5.webp',
	'/Kittens/Portrait/kitten6.webp',
	'/Kittens/Portrait/kitten7.webp',
	'/Kittens/Portrait/kitten8.webp',
	'/Kittens/Portrait/kitten9.webp',
	'/Kittens/Portrait/kitten10.webp',
	'/Kittens/Portrait/kitten12.webp',
	'/Kittens/Portrait/kitten13.webp',
	'/Kittens/Portrait/kitten14.webp',
	'/Kittens/Portrait/kitten15.webp',
	'/Kittens/Portrait/kitten16.webp',
	'/Kittens/Portrait/kitten17.webp',
	'/Kittens/Portrait/kitten18.webp',
	'/Kittens/Portrait/kitten19.webp',
	'/Kittens/Portrait/kitten20.webp',
	'/Kittens/Portrait/kitten22.webp',
	'/Kittens/Portrait/kitten26.webp',
	'/Kittens/Portrait/kitten27.webp',
	'/Kittens/Portrait/kitten28.webp',
	'/Kittens/Portrait/kitten29.webp'
];
